export const GENERATED_DISCOVER_ASSETS = {
  kitchen: [
    require("../assets/media/discover/generated/kitchen/kitchen-1.webp"),
    require("../assets/media/discover/generated/kitchen/kitchen-2.webp"),
    require("../assets/media/discover/generated/kitchen/kitchen-3.webp"),
    require("../assets/media/discover/generated/kitchen/kitchen-4.webp"),
    require("../assets/media/discover/generated/kitchen/kitchen-5.webp"),
    require("../assets/media/discover/generated/kitchen/kitchen-6.webp"),
    require("../assets/media/discover/generated/kitchen/kitchen-7.webp"),
  ],
  "living-room": [
    require("../assets/media/discover/generated/living-room/living-room-1.webp"),
    require("../assets/media/discover/generated/living-room/living-room-2.webp"),
    require("../assets/media/discover/generated/living-room/living-room-3.webp"),
    require("../assets/media/discover/generated/living-room/living-room-4.webp"),
    require("../assets/media/discover/generated/living-room/living-room-5.webp"),
    require("../assets/media/discover/generated/living-room/living-room-6.webp"),
    require("../assets/media/discover/generated/living-room/living-room-7.webp"),
  ],
  "dining-room": [
    require("../assets/media/discover/generated/dining-room/dining-room-1.webp"),
    require("../assets/media/discover/generated/dining-room/dining-room-2.webp"),
    require("../assets/media/discover/generated/dining-room/dining-room-3.webp"),
    require("../assets/media/discover/generated/dining-room/dining-room-4.webp"),
    require("../assets/media/discover/generated/dining-room/dining-room-5.webp"),
    require("../assets/media/discover/generated/dining-room/dining-room-6.webp"),
    require("../assets/media/discover/generated/dining-room/dining-room-7.webp"),
  ],
  bedroom: [
    require("../assets/media/discover/generated/bedroom/bedroom-1.webp"),
    require("../assets/media/discover/generated/bedroom/bedroom-2.webp"),
    require("../assets/media/discover/generated/bedroom/bedroom-3.webp"),
    require("../assets/media/discover/generated/bedroom/bedroom-4.webp"),
    require("../assets/media/discover/generated/bedroom/bedroom-5.webp"),
    require("../assets/media/discover/generated/bedroom/bedroom-6.webp"),
    require("../assets/media/discover/generated/bedroom/bedroom-7.webp"),
  ],
  bathroom: [
    require("../assets/media/discover/generated/master-suite/master-suite-1.webp"),
    require("../assets/media/discover/generated/master-suite/master-suite-2.webp"),
    require("../assets/media/discover/generated/master-suite/master-suite-3.webp"),
    require("../assets/media/discover/generated/master-suite/master-suite-4.webp"),
    require("../assets/media/discover/generated/master-suite/master-suite-5.webp"),
    require("../assets/media/discover/generated/master-suite/master-suite-6.webp"),
    require("../assets/media/discover/generated/master-suite/master-suite-7.webp"),
  ],
  "gaming-room": [
    require("../assets/media/discover/generated/gaming-room/gaming-room-1.webp"),
    require("../assets/media/discover/generated/gaming-room/gaming-room-2.webp"),
    require("../assets/media/discover/generated/gaming-room/gaming-room-3.webp"),
    require("../assets/media/discover/generated/gaming-room/gaming-room-4.webp"),
    require("../assets/media/discover/generated/gaming-room/gaming-room-5.webp"),
    require("../assets/media/discover/generated/gaming-room/gaming-room-6.webp"),
    require("../assets/media/discover/generated/gaming-room/gaming-room-7.webp"),
  ],
  "home-office": [
    require("../assets/media/discover/generated/home-office/home-office-1.webp"),
    require("../assets/media/discover/generated/home-office/home-office-2.webp"),
    require("../assets/media/discover/generated/home-office/home-office-3.webp"),
    require("../assets/media/discover/generated/home-office/home-office-4.webp"),
    require("../assets/media/discover/generated/home-office/home-office-5.webp"),
    require("../assets/media/discover/generated/home-office/home-office-6.webp"),
    require("../assets/media/discover/generated/home-office/home-office-7.webp"),
  ],
  "coffee-shop": [
    require("../assets/media/discover/generated/coffee-shop/coffee-shop-1.webp"),
    require("../assets/media/discover/generated/coffee-shop/coffee-shop-2.webp"),
    require("../assets/media/discover/generated/coffee-shop/coffee-shop-3.webp"),
    require("../assets/media/discover/generated/coffee-shop/coffee-shop-4.webp"),
    require("../assets/media/discover/generated/coffee-shop/coffee-shop-5.webp"),
    require("../assets/media/discover/generated/coffee-shop/coffee-shop-6.webp"),
    require("../assets/media/discover/generated/coffee-shop/coffee-shop-7.webp"),
  ],
  "study-room": [
    require("../assets/media/discover/generated/study-room/study-room-1.webp"),
    require("../assets/media/discover/generated/study-room/study-room-2.webp"),
    require("../assets/media/discover/generated/study-room/study-room-3.webp"),
    require("../assets/media/discover/generated/study-room/study-room-4.webp"),
    require("../assets/media/discover/generated/study-room/study-room-5.webp"),
    require("../assets/media/discover/generated/study-room/study-room-6.webp"),
    require("../assets/media/discover/generated/study-room/study-room-7.webp"),
  ],
  restaurant: [
    require("../assets/media/discover/generated/restaurant/restaurant-1.webp"),
    require("../assets/media/discover/generated/restaurant/restaurant-2.webp"),
    require("../assets/media/discover/generated/restaurant/restaurant-3.webp"),
    require("../assets/media/discover/generated/restaurant/restaurant-4.webp"),
    require("../assets/media/discover/generated/restaurant/restaurant-5.webp"),
    require("../assets/media/discover/generated/restaurant/restaurant-6.webp"),
    require("../assets/media/discover/generated/restaurant/restaurant-7.webp"),
  ],
  attic: [
    require("../assets/media/discover/generated/attic/attic-1.webp"),
    require("../assets/media/discover/generated/attic/attic-2.webp"),
    require("../assets/media/discover/generated/attic/attic-3.webp"),
    require("../assets/media/discover/generated/attic/attic-4.webp"),
    require("../assets/media/discover/generated/attic/attic-5.webp"),
    require("../assets/media/discover/generated/attic/attic-6.webp"),
    require("../assets/media/discover/generated/attic/attic-7.webp"),
  ],
  toilet: [
    require("../assets/media/discover/generated/bathroom/bathroom-1.webp"),
    require("../assets/media/discover/generated/bathroom/bathroom-2.webp"),
    require("../assets/media/discover/generated/bathroom/bathroom-3.webp"),
    require("../assets/media/discover/generated/bathroom/bathroom-4.webp"),
    require("../assets/media/discover/generated/bathroom/bathroom-5.webp"),
    require("../assets/media/discover/generated/bathroom/bathroom-6.webp"),
    require("../assets/media/discover/generated/bathroom/bathroom-7.webp"),
  ],
  balcony: [
    require("../assets/media/discover/generated/balcony/balcony-1.webp"),
    require("../assets/media/discover/generated/balcony/balcony-2.webp"),
    require("../assets/media/discover/generated/balcony/balcony-3.webp"),
    require("../assets/media/discover/generated/balcony/balcony-4.webp"),
    require("../assets/media/discover/generated/balcony/balcony-5.webp"),
    require("../assets/media/discover/generated/balcony/balcony-6.webp"),
    require("../assets/media/discover/generated/balcony/balcony-7.webp"),
  ],
  hall: [
    require("../assets/media/discover/generated/entryway/entryway-1.webp"),
    require("../assets/media/discover/generated/entryway/entryway-2.webp"),
    require("../assets/media/discover/generated/entryway/entryway-3.webp"),
    require("../assets/media/discover/generated/entryway/entryway-4.webp"),
    require("../assets/media/discover/generated/entryway/entryway-5.webp"),
    require("../assets/media/discover/generated/entryway/entryway-6.webp"),
    require("../assets/media/discover/generated/entryway/entryway-7.webp"),
  ],
  deck: [
    require("../assets/media/discover/generated/terrace/terrace-1.webp"),
    require("../assets/media/discover/generated/terrace/terrace-2.webp"),
    require("../assets/media/discover/generated/terrace/terrace-3.webp"),
    require("../assets/media/discover/generated/terrace/terrace-4.webp"),
    require("../assets/media/discover/generated/terrace/terrace-5.webp"),
    require("../assets/media/discover/generated/terrace/terrace-6.webp"),
    require("../assets/media/discover/generated/terrace/terrace-7.webp"),
  ],
  villa: [
    require("../assets/media/discover/generated/villa/villa-1.webp"),
    require("../assets/media/discover/generated/villa/villa-2.webp"),
    require("../assets/media/discover/generated/villa/villa-3.webp"),
    require("../assets/media/discover/generated/villa/villa-4.webp"),
    require("../assets/media/discover/generated/villa/villa-5.webp"),
    require("../assets/media/discover/generated/villa/villa-6.webp"),
    require("../assets/media/discover/generated/villa/villa-7.webp"),
  ],
  apartment: [
    require("../assets/media/discover/generated/apartment/apartment-1.webp"),
    require("../assets/media/discover/generated/apartment/apartment-2.webp"),
    require("../assets/media/discover/generated/apartment/apartment-3.webp"),
    require("../assets/media/discover/generated/apartment/apartment-4.webp"),
    require("../assets/media/discover/generated/apartment/apartment-5.webp"),
    require("../assets/media/discover/generated/apartment/apartment-6.webp"),
    require("../assets/media/discover/generated/apartment/apartment-7.webp"),
  ],
  house: [
    require("../assets/media/discover/generated/house/house-1.webp"),
    require("../assets/media/discover/generated/house/house-2.webp"),
    require("../assets/media/discover/generated/house/house-3.webp"),
    require("../assets/media/discover/generated/house/house-4.webp"),
    require("../assets/media/discover/generated/house/house-5.webp"),
    require("../assets/media/discover/generated/house/house-6.webp"),
    require("../assets/media/discover/generated/house/house-7.webp"),
  ],
  "office-building": [
    require("../assets/media/discover/generated/office-building/office-building-1.webp"),
    require("../assets/media/discover/generated/office-building/office-building-2.webp"),
    require("../assets/media/discover/generated/office-building/office-building-3.webp"),
    require("../assets/media/discover/generated/office-building/office-building-4.webp"),
    require("../assets/media/discover/generated/office-building/office-building-5.webp"),
    require("../assets/media/discover/generated/office-building/office-building-6.webp"),
    require("../assets/media/discover/generated/office-building/office-building-7.webp"),
  ],
  retail: [
    require("../assets/media/discover/generated/retail/retail-1.webp"),
    require("../assets/media/discover/generated/retail/retail-2.webp"),
    require("../assets/media/discover/generated/retail/retail-3.webp"),
    require("../assets/media/discover/generated/retail/retail-4.webp"),
    require("../assets/media/discover/generated/retail/retail-5.webp"),
    require("../assets/media/discover/generated/retail/retail-6.webp"),
    require("../assets/media/discover/generated/retail/retail-7.webp"),
  ],
  residential: [
    require("../assets/media/discover/generated/exterior/exterior-1.webp"),
    require("../assets/media/discover/generated/exterior/exterior-2.webp"),
    require("../assets/media/discover/generated/exterior/exterior-3.webp"),
    require("../assets/media/discover/generated/exterior/exterior-4.webp"),
    require("../assets/media/discover/generated/exterior/exterior-5.webp"),
    require("../assets/media/discover/generated/exterior/exterior-6.webp"),
    require("../assets/media/discover/generated/exterior/exterior-7.webp"),
  ],
  wall: [
    require("../assets/media/discover/wall-scenes/sage-green-suite.webp"),
    require("../assets/media/discover/wall-scenes/midnight-navy-bedroom.webp"),
    require("../assets/media/discover/wall-scenes/terracotta-dining.webp"),
    require("../assets/media/discover/wall-scenes/dusty-rose-retreat.webp"),
    require("../assets/media/discover/wall-scenes/gallery-charcoal-lounge.webp"),
    require("../assets/media/discover/wall-scenes/soft-ivory-kitchen.webp"),
    require("../assets/media/discover/wall-scenes/deep-olive-study.webp"),
  ],
  floor: [
    require("../assets/media/discover/floor-scenes/natural-oak-parquet.webp"),
    require("../assets/media/discover/floor-scenes/heritage-walnut-plank.webp"),
    require("../assets/media/discover/floor-scenes/polished-carrara-marble.webp"),
    require("../assets/media/discover/floor-scenes/industrial-gray-concrete.webp"),
    require("../assets/media/discover/floor-scenes/walnut-chevron.webp"),
    require("../assets/media/discover/floor-scenes/terracotta-atelier-tile.webp"),
    require("../assets/media/discover/floor-scenes/modern-slate-tile.webp"),
  ],
  garden: [
    require("../assets/media/discover/generated/garden/garden-1.webp"),
    require("../assets/media/discover/generated/garden/garden-2.webp"),
    require("../assets/media/discover/generated/garden/garden-3.webp"),
    require("../assets/media/discover/generated/garden/garden-4.webp"),
    require("../assets/media/discover/generated/garden/garden-5.webp"),
    require("../assets/media/discover/generated/garden/garden-6.webp"),
    require("../assets/media/discover/generated/garden/garden-7.webp"),
  ],
} as const;

export type GeneratedDiscoverAssetId = keyof typeof GENERATED_DISCOVER_ASSETS;
