export const GENERATED_DISCOVER_ASSETS = {
  kitchen: [
    require("../assets/media/discover/generated/kitchen/kitchen-1.jpg"),
    require("../assets/media/discover/generated/kitchen/kitchen-2.jpg"),
    require("../assets/media/discover/generated/kitchen/kitchen-3.jpg"),
    require("../assets/media/discover/generated/kitchen/kitchen-4.jpg"),
    require("../assets/media/discover/generated/kitchen/kitchen-5.jpg"),
    require("../assets/media/discover/generated/kitchen/kitchen-6.jpg"),
    require("../assets/media/discover/generated/kitchen/kitchen-7.jpg"),
  ],
  "living-room": [
    require("../assets/media/discover/generated/living-room/living-room-1.jpg"),
    require("../assets/media/discover/generated/living-room/living-room-2.jpg"),
    require("../assets/media/discover/generated/living-room/living-room-3.jpg"),
    require("../assets/media/discover/generated/living-room/living-room-4.jpg"),
    require("../assets/media/discover/generated/living-room/living-room-5.jpg"),
    require("../assets/media/discover/generated/living-room/living-room-6.jpg"),
    require("../assets/media/discover/generated/living-room/living-room-7.jpg"),
  ],
  "dining-room": [
    require("../assets/media/discover/generated/dining-room/dining-room-1.jpg"),
    require("../assets/media/discover/generated/dining-room/dining-room-2.jpg"),
    require("../assets/media/discover/generated/dining-room/dining-room-3.jpg"),
    require("../assets/media/discover/generated/dining-room/dining-room-4.jpg"),
    require("../assets/media/discover/generated/dining-room/dining-room-5.jpg"),
    require("../assets/media/discover/generated/dining-room/dining-room-6.jpg"),
    require("../assets/media/discover/generated/dining-room/dining-room-7.jpg"),
  ],
  bedroom: [
    require("../assets/media/discover/generated/bedroom/bedroom-1.jpg"),
    require("../assets/media/discover/generated/bedroom/bedroom-2.jpg"),
    require("../assets/media/discover/generated/bedroom/bedroom-3.jpg"),
    require("../assets/media/discover/generated/bedroom/bedroom-4.jpg"),
    require("../assets/media/discover/generated/bedroom/bedroom-5.jpg"),
    require("../assets/media/discover/generated/bedroom/bedroom-6.jpg"),
    require("../assets/media/discover/generated/bedroom/bedroom-7.jpg"),
  ],
  bathroom: [
    require("../assets/media/discover/generated/master-suite/master-suite-1.jpg"),
    require("../assets/media/discover/generated/master-suite/master-suite-2.jpg"),
    require("../assets/media/discover/generated/master-suite/master-suite-3.jpg"),
    require("../assets/media/discover/generated/master-suite/master-suite-4.jpg"),
    require("../assets/media/discover/generated/master-suite/master-suite-5.jpg"),
    require("../assets/media/discover/generated/master-suite/master-suite-6.jpg"),
    require("../assets/media/discover/generated/master-suite/master-suite-7.jpg"),
  ],
  "gaming-room": [
    require("../assets/media/discover/generated/gaming-room/gaming-room-1.jpg"),
    require("../assets/media/discover/generated/gaming-room/gaming-room-2.jpg"),
    require("../assets/media/discover/generated/gaming-room/gaming-room-3.jpg"),
    require("../assets/media/discover/generated/gaming-room/gaming-room-4.jpg"),
    require("../assets/media/discover/generated/gaming-room/gaming-room-5.jpg"),
    require("../assets/media/discover/generated/gaming-room/gaming-room-6.jpg"),
    require("../assets/media/discover/generated/gaming-room/gaming-room-7.jpg"),
  ],
  "home-office": [
    require("../assets/media/discover/generated/home-office/home-office-1.jpg"),
    require("../assets/media/discover/generated/home-office/home-office-2.jpg"),
    require("../assets/media/discover/generated/home-office/home-office-3.jpg"),
    require("../assets/media/discover/generated/home-office/home-office-4.jpg"),
    require("../assets/media/discover/generated/home-office/home-office-5.jpg"),
    require("../assets/media/discover/generated/home-office/home-office-6.jpg"),
    require("../assets/media/discover/generated/home-office/home-office-7.jpg"),
  ],
  "coffee-shop": [
    require("../assets/media/discover/generated/coffee-shop/coffee-shop-1.jpg"),
    require("../assets/media/discover/generated/coffee-shop/coffee-shop-2.jpg"),
    require("../assets/media/discover/generated/coffee-shop/coffee-shop-3.jpg"),
    require("../assets/media/discover/generated/coffee-shop/coffee-shop-4.jpg"),
    require("../assets/media/discover/generated/coffee-shop/coffee-shop-5.jpg"),
    require("../assets/media/discover/generated/coffee-shop/coffee-shop-6.jpg"),
    require("../assets/media/discover/generated/coffee-shop/coffee-shop-7.jpg"),
  ],
  "study-room": [
    require("../assets/media/discover/generated/study-room/study-room-1.jpg"),
    require("../assets/media/discover/generated/study-room/study-room-2.jpg"),
    require("../assets/media/discover/generated/study-room/study-room-3.jpg"),
    require("../assets/media/discover/generated/study-room/study-room-4.jpg"),
    require("../assets/media/discover/generated/study-room/study-room-5.jpg"),
    require("../assets/media/discover/generated/study-room/study-room-6.jpg"),
    require("../assets/media/discover/generated/study-room/study-room-7.jpg"),
  ],
  restaurant: [
    require("../assets/media/discover/generated/restaurant/restaurant-1.jpg"),
    require("../assets/media/discover/generated/restaurant/restaurant-2.jpg"),
    require("../assets/media/discover/generated/restaurant/restaurant-3.jpg"),
    require("../assets/media/discover/generated/restaurant/restaurant-4.jpg"),
    require("../assets/media/discover/generated/restaurant/restaurant-5.jpg"),
    require("../assets/media/discover/generated/restaurant/restaurant-6.jpg"),
    require("../assets/media/discover/generated/restaurant/restaurant-7.jpg"),
  ],
  attic: [
    require("../assets/media/discover/generated/attic/attic-1.jpg"),
    require("../assets/media/discover/generated/attic/attic-2.jpg"),
    require("../assets/media/discover/generated/attic/attic-3.jpg"),
    require("../assets/media/discover/generated/attic/attic-4.jpg"),
    require("../assets/media/discover/generated/attic/attic-5.jpg"),
    require("../assets/media/discover/generated/attic/attic-6.jpg"),
    require("../assets/media/discover/generated/attic/attic-7.jpg"),
  ],
  toilet: [
    require("../assets/media/discover/generated/bathroom/bathroom-1.jpg"),
    require("../assets/media/discover/generated/bathroom/bathroom-2.jpg"),
    require("../assets/media/discover/generated/bathroom/bathroom-3.jpg"),
    require("../assets/media/discover/generated/bathroom/bathroom-4.jpg"),
    require("../assets/media/discover/generated/bathroom/bathroom-5.jpg"),
    require("../assets/media/discover/generated/bathroom/bathroom-6.jpg"),
    require("../assets/media/discover/generated/bathroom/bathroom-7.jpg"),
  ],
  balcony: [
    require("../assets/media/discover/generated/balcony/balcony-1.jpg"),
    require("../assets/media/discover/generated/balcony/balcony-2.jpg"),
    require("../assets/media/discover/generated/balcony/balcony-3.jpg"),
    require("../assets/media/discover/generated/balcony/balcony-4.jpg"),
    require("../assets/media/discover/generated/balcony/balcony-5.jpg"),
    require("../assets/media/discover/generated/balcony/balcony-6.jpg"),
    require("../assets/media/discover/generated/balcony/balcony-7.jpg"),
  ],
  hall: [
    require("../assets/media/discover/generated/entryway/entryway-1.jpg"),
    require("../assets/media/discover/generated/entryway/entryway-2.jpg"),
    require("../assets/media/discover/generated/entryway/entryway-3.jpg"),
    require("../assets/media/discover/generated/entryway/entryway-4.jpg"),
    require("../assets/media/discover/generated/entryway/entryway-5.jpg"),
    require("../assets/media/discover/generated/entryway/entryway-6.jpg"),
    require("../assets/media/discover/generated/entryway/entryway-7.jpg"),
  ],
  deck: [
    require("../assets/media/discover/generated/terrace/terrace-1.jpg"),
    require("../assets/media/discover/generated/terrace/terrace-2.jpg"),
    require("../assets/media/discover/generated/terrace/terrace-3.jpg"),
    require("../assets/media/discover/generated/terrace/terrace-4.jpg"),
    require("../assets/media/discover/generated/terrace/terrace-5.jpg"),
    require("../assets/media/discover/generated/terrace/terrace-6.jpg"),
    require("../assets/media/discover/generated/terrace/terrace-7.jpg"),
  ],
  villa: [
    require("../assets/media/discover/generated/villa/villa-1.jpg"),
    require("../assets/media/discover/generated/villa/villa-2.jpg"),
    require("../assets/media/discover/generated/villa/villa-3.jpg"),
    require("../assets/media/discover/generated/villa/villa-4.jpg"),
    require("../assets/media/discover/generated/villa/villa-5.jpg"),
    require("../assets/media/discover/generated/villa/villa-6.jpg"),
    require("../assets/media/discover/generated/villa/villa-7.jpg"),
  ],
  apartment: [
    require("../assets/media/discover/generated/apartment/apartment-1.jpg"),
    require("../assets/media/discover/generated/apartment/apartment-2.jpg"),
    require("../assets/media/discover/generated/apartment/apartment-3.jpg"),
    require("../assets/media/discover/generated/apartment/apartment-4.jpg"),
    require("../assets/media/discover/generated/apartment/apartment-5.jpg"),
    require("../assets/media/discover/generated/apartment/apartment-6.jpg"),
    require("../assets/media/discover/generated/apartment/apartment-7.jpg"),
  ],
  house: [
    require("../assets/media/discover/generated/house/house-1.jpg"),
    require("../assets/media/discover/generated/house/house-2.jpg"),
    require("../assets/media/discover/generated/house/house-3.jpg"),
    require("../assets/media/discover/generated/house/house-4.jpg"),
    require("../assets/media/discover/generated/house/house-5.jpg"),
    require("../assets/media/discover/generated/house/house-6.jpg"),
    require("../assets/media/discover/generated/house/house-7.jpg"),
  ],
  "office-building": [
    require("../assets/media/discover/generated/office-building/office-building-1.jpg"),
    require("../assets/media/discover/generated/office-building/office-building-2.jpg"),
    require("../assets/media/discover/generated/office-building/office-building-3.jpg"),
    require("../assets/media/discover/generated/office-building/office-building-4.jpg"),
    require("../assets/media/discover/generated/office-building/office-building-5.jpg"),
    require("../assets/media/discover/generated/office-building/office-building-6.jpg"),
    require("../assets/media/discover/generated/office-building/office-building-7.jpg"),
  ],
  retail: [
    require("../assets/media/discover/generated/retail/retail-1.jpg"),
    require("../assets/media/discover/generated/retail/retail-2.jpg"),
    require("../assets/media/discover/generated/retail/retail-3.jpg"),
    require("../assets/media/discover/generated/retail/retail-4.jpg"),
    require("../assets/media/discover/generated/retail/retail-5.jpg"),
    require("../assets/media/discover/generated/retail/retail-6.jpg"),
    require("../assets/media/discover/generated/retail/retail-7.jpg"),
  ],
  residential: [
    require("../assets/media/discover/generated/exterior/exterior-1.jpg"),
    require("../assets/media/discover/generated/exterior/exterior-2.jpg"),
    require("../assets/media/discover/generated/exterior/exterior-3.jpg"),
    require("../assets/media/discover/generated/exterior/exterior-4.jpg"),
    require("../assets/media/discover/generated/exterior/exterior-5.jpg"),
    require("../assets/media/discover/generated/exterior/exterior-6.jpg"),
    require("../assets/media/discover/generated/exterior/exterior-7.jpg"),
  ],
  wall: [
    require("../assets/media/discover/wall-scenes/sage-green-suite.jpg"),
    require("../assets/media/discover/wall-scenes/midnight-navy-bedroom.jpg"),
    require("../assets/media/discover/wall-scenes/terracotta-dining.jpg"),
    require("../assets/media/discover/wall-scenes/dusty-rose-retreat.jpg"),
    require("../assets/media/discover/wall-scenes/gallery-charcoal-lounge.jpg"),
    require("../assets/media/discover/wall-scenes/soft-ivory-kitchen.jpg"),
    require("../assets/media/discover/wall-scenes/deep-olive-study.jpg"),
  ],
  floor: [
    require("../assets/media/discover/floor-scenes/natural-oak-parquet.jpg"),
    require("../assets/media/discover/floor-scenes/heritage-walnut-plank.jpg"),
    require("../assets/media/discover/floor-scenes/polished-carrara-marble.jpg"),
    require("../assets/media/discover/floor-scenes/industrial-gray-concrete.jpg"),
    require("../assets/media/discover/floor-scenes/walnut-chevron.jpg"),
    require("../assets/media/discover/floor-scenes/terracotta-atelier-tile.jpg"),
    require("../assets/media/discover/floor-scenes/modern-slate-tile.jpg"),
  ],
  garden: [
    require("../assets/media/discover/generated/garden/garden-1.jpg"),
    require("../assets/media/discover/generated/garden/garden-2.jpg"),
    require("../assets/media/discover/generated/garden/garden-3.jpg"),
    require("../assets/media/discover/generated/garden/garden-4.jpg"),
    require("../assets/media/discover/generated/garden/garden-5.jpg"),
    require("../assets/media/discover/generated/garden/garden-6.jpg"),
    require("../assets/media/discover/generated/garden/garden-7.jpg"),
  ],
} as const;

export type GeneratedDiscoverAssetId = keyof typeof GENERATED_DISCOVER_ASSETS;
